schemaVersion: 2.1.0
metadata:
  generateName: hpgrahsl-poi-map-app
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: development-tooling
    container:
      endpoints:
        - name: http-angular
          targetPort: 4200
      image: registry.access.redhat.com/ubi8/nodejs-18:1-32
      args: ["tail", "-f", "/dev/null"]
      memoryLimit: 1024Mi
  - name: runtime
commands:
  - exec:
      commandLine: npm install
      component: runtime
      group:
        isDefault: true
        kind: build
      workingDir: ${PROJECT_SOURCE}
    id: install
  - exec:
      commandLine: npm run start
      component: runtime
      group:
        isDefault: true
        kind: run
      hotReloadCapable: true
      workingDir: ${PROJECT_SOURCE}
    id: run
